using AppPlugin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Threading;

namespace Sample.Definition
{
    public abstract class StringPluginsWithOptions : AbstractPlugin<string, string, TransfareOptions, double>
    {

        public const String PLUGIN_NAME = "Sample.StringPluginsWithOptions";

        protected sealed override Task<string> ExecuteAsync(string input, TransfareOptions options, IProgress<double> progress, CancellationToken cancelToken)
        {
            if (options.OptionsIdentifyer != GetOptionsGuid())
                throw new ArgumentException("Option Not generated by this Plugin", nameof(options));
            return ExecuteAsync(input, options.Options, progress, cancelToken);
        }

        protected sealed override async Task<TransfareOptions> GetDefaultOptionsAsync()
        => new TransfareOptions() { Options = await GetOptions() };

        protected abstract Task<string> ExecuteAsync(string input, Options options, IProgress<double> progress, CancellationToken cancelToken);

        protected abstract Task<Options> GetOptions();
        protected abstract Guid GetOptionsGuid();
    }
}
